# Use the official Node.js image from the Docker Hub
FROM node:14

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image
COPY package*.json ./

# Install dependencies
RUN npm install 

# Copy local code to the container image
COPY . .

# Run the web service on container startup
CMD [ "node", "server.js" ]

# Inform Docker that the container listens on port 80
EXPOSE 80